export function loginPage(error = "") {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Fima Admin Login</title>
  <style>
    *{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:radial-gradient(circle at 20% 0%,#40207855,transparent 38%),linear-gradient(180deg,#070510,#05040b);color:#f8f3ff;font-family:Inter,Segoe UI,sans-serif}
    form{width:min(440px,calc(100vw - 32px));padding:30px;border:1px solid #6e55a055;border-radius:10px;background:linear-gradient(145deg,#171027ee,#090611f5);box-shadow:0 24px 90px #000a,0 0 48px #8b5cff22}
    h1{margin:0 0 10px;font-size:32px;line-height:1}.muted{color:#b9a9cd}.mark{display:inline-grid;place-items:center;width:42px;height:42px;margin-bottom:18px;border-radius:9px;background:linear-gradient(135deg,#d7a6ff,#53d6ff);color:#090611;font-weight:950}
    label{display:block;margin:22px 0 8px;font-weight:900}input,button{width:100%;height:48px;border-radius:8px;font:inherit}input{padding:0 13px;color:#fff;background:#090612;border:1px solid #493560}.password-field{position:relative;display:block}.password-field input{padding-right:52px}.password-toggle{position:absolute;right:7px;top:50%;width:38px;height:36px;transform:translateY(-50%);border:1px solid transparent;background:transparent;color:#b9a9cd}.password-toggle:hover{border-color:#6e55a055;background:#ffffff10;color:#fff}.password-toggle svg{width:20px;height:20px;fill:currentColor}
    button{margin-top:14px;border:0;font-weight:950;background:linear-gradient(135deg,#d7a6ff,#53d6ff);color:#090611;cursor:pointer}.error{padding:10px 12px;border:1px solid #ff7b9366;border-radius:8px;background:#40101a;color:#ff9caf}
  </style>
</head>
<body>
  <form method="post" action="/admin/login">
    <div class="mark">FM</div>
    <h1>Fima Admin</h1>
    <p class="muted">Sales, licenses, downloads and security.</p>
    ${error ? `<p class="error">${escapeHtml(error)}</p>` : ""}
    <label for="password">Admin password</label>
    <span class="password-field"><input id="password" name="password" type="password" autocomplete="current-password" required><button class="password-toggle" type="button" aria-label="Show password" title="Show password"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M12 5c5.2 0 8.7 4.7 9.8 6.4.3.4.3.8 0 1.2C20.7 14.3 17.2 19 12 19s-8.7-4.7-9.8-6.4a1 1 0 0 1 0-1.2C3.3 9.7 6.8 5 12 5Zm0 2C8.2 7 5.4 10.1 4.3 12c1.1 1.9 3.9 5 7.7 5s6.6-3.1 7.7-5C18.6 10.1 15.8 7 12 7Zm0 2.5a2.5 2.5 0 1 1 0 5 2.5 2.5 0 0 1 0-5Z"/></svg></button></span>
    <button type="submit">Login</button>
  </form>
  <script>document.querySelector('.password-toggle')?.addEventListener('click',function(){const input=document.getElementById('password');const show=input.type==='password';input.type=show?'text':'password';this.setAttribute('aria-label',show?'Hide password':'Show password');this.title=show?'Hide password':'Show password';input.focus();});</script>
</body>
</html>`;
}

export function adminPage() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Fima Macro Admin</title>
  <style>
    :root{--bg:#06050c;--panel:#110c1c;--panel2:#171026;--line:#6e55a033;--text:#f8f3ff;--muted:#b8aacb;--faint:#756a88;--primary:#b477ff;--accent:#53d6ff;--good:#72f0c4;--bad:#ff7b93;--warn:#ffd66f;--radius:8px}
    *{box-sizing:border-box}body{margin:0;color:var(--text);font-family:Inter,Segoe UI,sans-serif;background:radial-gradient(circle at 12% 0%,#5f2db244,transparent 34%),radial-gradient(circle at 90% 8%,#35cce833,transparent 28%),linear-gradient(180deg,#080713,#05040a);line-height:1.45}
    button,input,select,textarea{font:inherit}button{cursor:pointer}code{font-family:Consolas,monospace;color:#dcb8ff}
    .layout{min-height:100vh;display:grid;grid-template-columns:250px minmax(0,1fr)}
    aside{position:sticky;top:0;height:100vh;padding:18px;border-right:1px solid #ffffff12;background:#080611e8;backdrop-filter:blur(18px)}
    .brand{display:flex;align-items:center;gap:12px;margin-bottom:22px}.brand-mark{display:grid;place-items:center;width:40px;height:40px;border-radius:9px;background:linear-gradient(135deg,var(--primary),var(--accent));color:#070510;font-weight:950}.brand strong{display:block}.brand span{color:var(--muted);font-size:12px}
    .nav{display:grid;gap:7px}.nav button{height:42px;padding:0 12px;border:1px solid transparent;border-radius:var(--radius);background:transparent;color:var(--muted);text-align:left;font-weight:850}.nav button:hover,.nav button.active{color:var(--text);border-color:var(--line);background:linear-gradient(135deg,#a25cff22,#ffffff08)}
    .logout{position:absolute;left:18px;right:18px;bottom:18px}.logout button,.btn{height:40px;padding:0 13px;border:1px solid var(--line);border-radius:var(--radius);background:#ffffff0a;color:var(--text);font-weight:850}.btn.primary{border:0;color:#070510;background:linear-gradient(135deg,#d7a6ff,#53d6ff)}.btn.danger{border-color:#ff7b9366;background:#3a111c}.btn.good{border-color:#72f0c466;background:#103527}.btn:disabled{opacity:.55;cursor:not-allowed}
    main{min-width:0;padding:22px}.topbar{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:18px}.topbar h1{margin:0;font-size:30px;line-height:1}.topbar p{margin:4px 0 0;color:var(--muted)}
    .panel{border:1px solid var(--line);border-radius:10px;background:linear-gradient(145deg,#ffffff09,#ffffff03),#0d0917;box-shadow:0 18px 60px #0006}.panel-pad{padding:16px}.section{display:none}.section.active{display:grid;gap:16px}
    .cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.card{padding:15px;border:1px solid var(--line);border-radius:var(--radius);background:linear-gradient(135deg,#a25cff18,#53d6ff0a),#0f0a19}.card span{display:block;color:var(--faint);font-size:12px;font-weight:900;text-transform:uppercase;letter-spacing:.06em}.card strong{display:block;margin-top:7px;font-size:24px}
    .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.grid3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.filters{display:grid;grid-template-columns:2fr repeat(4,minmax(130px,1fr));gap:8px;margin-bottom:12px}
    input,select,textarea{width:100%;min-height:40px;padding:0 11px;color:var(--text);border:1px solid var(--line);border-radius:var(--radius);background:#070510}textarea{min-height:92px;padding:10px;resize:vertical}
    input[type="checkbox"]{width:18px;min-width:18px;height:18px;min-height:18px;padding:0;margin:0;accent-color:var(--primary);vertical-align:middle}.check-row{display:flex;align-items:center;gap:10px;min-height:40px;padding:9px 11px;border:1px solid var(--line);border-radius:var(--radius);background:#070510;color:var(--text);font-weight:850}.check-row input{flex:0 0 auto}.form-actions{display:flex;flex-wrap:wrap;align-items:center;gap:10px;margin-top:12px}.form-label{display:grid;gap:7px;color:var(--muted);font-weight:850}.table-wrap{width:100%;overflow:auto}
    table{width:100%;min-width:760px;border-collapse:collapse}th,td{padding:11px 10px;border-bottom:1px solid #ffffff10;text-align:left;vertical-align:top;font-size:13px}th{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.05em}td .muted{font-size:12px}.warn-text{color:var(--warn)}.danger-text{color:var(--bad)}.status{display:inline-flex;min-height:24px;align-items:center;padding:0 8px;border-radius:999px;font-size:12px;font-weight:900}.status.active,.status.valid,.status.success,.status.live{background:#12392d;color:var(--good)}.status.banned,.status.failed{background:#3b101c;color:var(--bad)}.status.inactive,.status.expired,.status.test{background:#3f3211;color:var(--warn)}
    .actions{display:flex;flex-wrap:wrap;gap:6px}.actions .btn{height:32px;padding:0 9px;font-size:12px}.empty{padding:22px;border:1px dashed var(--line);border-radius:var(--radius);color:var(--muted);text-align:center}.loading{color:var(--muted)}.bars{display:grid;gap:8px}.bar{display:grid;grid-template-columns:110px 1fr 64px;gap:10px;align-items:center}.bar-track{height:9px;border-radius:999px;background:#ffffff12;overflow:hidden}.bar-fill{height:100%;border-radius:999px;background:linear-gradient(90deg,var(--primary),var(--accent))}
    .modal{position:fixed;inset:0;display:none;place-items:center;padding:18px;background:#05030bcc;z-index:20}.modal.show{display:grid}.dialog{width:min(880px,100%);max-height:88vh;overflow:auto}.detail{white-space:pre-wrap;color:var(--muted);font-size:13px}
    @media(max-width:1050px){.layout{grid-template-columns:1fr}aside{position:relative;height:auto}.logout{position:static;margin-top:14px}.cards{grid-template-columns:repeat(2,1fr)}.grid2,.grid3,.filters{grid-template-columns:1fr}.hide-sm{display:none}}
    @media(max-width:560px){main{padding:14px}.cards{grid-template-columns:1fr}.topbar{align-items:flex-start;flex-direction:column}th,td{font-size:12px;padding:9px 7px}.brand span{display:none}}
  </style>
</head>
<body>
  <div class="layout">
    <aside>
      <div class="brand"><div class="brand-mark">FM</div><div><strong>Fima Macro</strong><span>Admin Control</span></div></div>
      <div class="nav" id="nav"></div>
      <form class="logout" method="post" action="/admin/logout"><button type="submit">Logout</button></form>
    </aside>
    <main>
      <div class="topbar"><div><h1 id="pageTitle">Dashboard</h1><p id="pageSubtitle">Sales, licenses and system health.</p></div><button class="btn primary" onclick="refreshCurrent()">Refresh</button></div>
      <section class="section active" id="dashboard"></section>
      <section class="section" id="products"></section>
      <section class="section" id="users"></section>
      <section class="section" id="purchases"></section>
      <section class="section" id="orders"></section>
      <section class="section" id="licenses"></section>
      <section class="section" id="customers"></section>
      <section class="section" id="downloads"></section>
      <section class="section" id="settings"></section>
      <section class="section" id="coupons"></section>
      <section class="section" id="giftCodes"></section>
      <section class="section" id="directGifts"></section>
      <section class="section" id="referrals"></section>
      <section class="section" id="analytics"></section>
      <section class="section" id="webhooks"></section>
      <section class="section" id="audit"></section>
      <section class="section" id="permissions"></section>
      <section class="section" id="tools"></section>
    </main>
  </div>
  <div class="modal" id="modal" onclick="if(event.target===this) closeModal()"><div class="dialog panel panel-pad"><div class="actions" style="justify-content:space-between"><strong id="modalTitle">Details</strong><button class="btn" onclick="closeModal()">Close</button></div><pre class="detail" id="modalBody"></pre></div></div>
  <script>
    const sections = [
      ['dashboard','Dashboard','Revenue, health and recent activity.'],
      ['products','Products','Create Stripe products, EUR prices and store visibility.'],
      ['users','Users','Registered accounts, Stripe customer IDs and roles.'],
      ['purchases','Purchases','Product purchases linked to user accounts.'],
      ['orders','Orders','Payments, Stripe sessions and customer plans.'],
      ['licenses','Licenses','License keys, HWID, validation and download history.'],
      ['customers','Customers','Emails, spend, orders and notes.'],
      ['downloads','Downloads / Versions','Current manifest, release info and download logs.'],
      ['settings','Site Settings','Public website and checkout switches.'],
      ['coupons','Coupons / Discounts','Manual coupon and promotion-code preparation.'],
      ['giftCodes','Gift Codes','Create one-time gift codes and inspect redemptions.'],
      ['directGifts','Direct Gifts','Send pending packages to registered Fima accounts.'],
      ['referrals','Referrals','Invite codes, verification status and 15-day rewards.'],
      ['analytics','Analytics','Events, validations, downloads and checkout signals.'],
      ['webhooks','Webhook / Stripe Logs','Stripe webhook processing and failures.'],
      ['audit','Security / Audit Logs','Admin actions and system security log.'],
      ['permissions','Roles & Permissions','RBAC role presets, dangerous permissions and enforcement status.'],
      ['tools','Manual Tools','Create licenses and quick admin actions.']
    ];
    let current = 'dashboard';
    const $ = (id) => document.getElementById(id);
    const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const money = (cents, currency='usd') => new Intl.NumberFormat('en-US',{style:'currency',currency:String(currency||'usd').toUpperCase()}).format((cents||0)/100);
    const date = (v) => v ? new Date(v).toLocaleString() : '-';
    const short = (v,n=18) => !v ? '-' : String(v).length>n ? String(v).slice(0,n)+'...' : String(v);
    const maskEmail = (v) => { const text=String(v||'').trim(); const parts=text.split('@'); if(parts.length!==2) return text?short(text,12):'-'; const local=parts[0]||''; return (local.slice(0,1)||'*')+'***'+(local.length>2?local.slice(-1):'')+'@'+parts[1]; };
    const maskCode = (v) => { const text=String(v||'').trim(); const last=text.replace(/[^A-Za-z0-9]/g,'').slice(-4); return last ? 'FIMA-****-****-'+last : '-'; };
    const maskId = (v) => { const text=String(v||'').trim(); return text.length>8 ? text.slice(0,4)+'***'+text.slice(-4) : (text?'***':'-'); };
    const pill = (v) => '<span class="status '+esc(v||'')+'">'+esc(v||'-')+'</span>';
    let csrfTokenPromise = null;
    async function csrfToken(){
      if(!csrfTokenPromise){
        csrfTokenPromise = fetch('/admin/api/csrf-token',{credentials:'same-origin',cache:'no-store'})
          .then(async res => {
            const data = await res.json().catch(()=>({}));
            if(!res.ok || !data.csrfToken) throw new Error('CSRF token unavailable');
            return data.csrfToken;
          })
          .catch(error => { csrfTokenPromise=null; throw error; });
      }
      return csrfTokenPromise;
    }
    async function api(path, options={}) {
      const method = String(options.method || 'GET').toUpperCase();
      const headers = {'content-type':'application/json', ...(options.headers || {})};
      if(!['GET','HEAD','OPTIONS'].includes(method)){
        headers['x-fima-csrf'] = await csrfToken();
      }
      const res = await fetch(path,{credentials:'same-origin',...options,headers});
      const data = await res.json().catch(()=>({}));
      if(!res.ok) throw new Error(data.error || data.message || 'Request failed');
      return data;
    }
    function setLoading(id){ $(id).innerHTML='<div class="panel panel-pad loading">Loading...</div>'; }
    function showSectionError(id, error){
      const message = error && error.message ? error.message : 'Request failed';
      $(id).innerHTML='<div class="panel panel-pad"><h3>Admin data could not load</h3><p class="muted">'+esc(message)+'</p><button class="btn primary" onclick="refreshCurrent()">Try again</button></div>';
    }
    function empty(text){ return '<div class="empty">'+esc(text)+'</div>'; }
    function table(headers, rows, emptyText='No records yet.') {
      if(!rows.length) return empty(emptyText);
      return '<div class="panel panel-pad"><div class="table-wrap"><table><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table></div></div>';
    }
    function showModal(title, data){ $('modalTitle').textContent=title; $('modalBody').textContent=typeof data==='string'?data:JSON.stringify(data,null,2); $('modal').classList.add('show'); }
    function closeModal(){ $('modal').classList.remove('show'); }
    function switchTo(id){ current=id; document.querySelectorAll('.section').forEach(s=>s.classList.toggle('active',s.id===id)); document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.id===id)); const meta=sections.find(s=>s[0]===id); $('pageTitle').textContent=meta[1]; $('pageSubtitle').textContent=meta[2]; refreshCurrent(); }
    function refreshCurrent(){
      const loader = ({dashboard:loadDashboard,products:loadProducts,users:loadUsers,purchases:loadPurchases,orders:loadOrders,licenses:loadLicenses,customers:loadCustomers,downloads:loadDownloads,settings:loadSettings,coupons:loadCoupons,giftCodes:loadGiftCodes,directGifts:loadDirectGifts,referrals:loadReferrals,analytics:loadAnalytics,webhooks:loadWebhooks,audit:loadAudit,permissions:loadPermissions,tools:loadTools}[current]);
      Promise.resolve(loader()).catch((error)=>showSectionError(current,error));
    }
    $('nav').innerHTML = sections.map(([id,label]) => '<button data-id="'+id+'" class="'+(id==='dashboard'?'active':'')+'" onclick="switchTo(\\''+id+'\\')">'+label+'</button>').join('');

    async function loadDashboard(){
      setLoading('dashboard'); const d=await api('/admin/api/dashboard');
      const c=d.cards; const cards=[['Total revenue',money(c.totalRevenue)],['Today revenue',money(c.todayRevenue)],['Week revenue',money(c.weekRevenue)],['Month revenue',money(c.monthRevenue)],['Orders',c.totalOrders],['Licenses',c.totalLicenses],['Active licenses',c.activeLicenses],['Expired licenses',c.expiredLicenses],['Banned licenses',c.bannedLicenses],['Lifetime',c.lifetimeLicenses],['Most sold plan',c.mostSoldPlan],['Downloads',c.downloadCount],['Active users 24h',c.activeUsersLast24h],['Failed webhooks',c.failedWebhookCount],['Failed checkouts',c.failedCheckoutCount],['HWID mismatches',c.hwidMismatchCount]];
      $('dashboard').innerHTML='<div class="cards">'+cards.map(x=>'<div class="card"><span>'+esc(x[0])+'</span><strong>'+esc(x[1])+'</strong></div>').join('')+'</div><div class="grid2"><div class="panel panel-pad"><h3>Revenue by day</h3>'+bars(d.charts.revenueByDay.map(x=>[x.date,money(x.revenue),x.revenue]))+'</div><div class="panel panel-pad"><h3>Orders by plan</h3>'+bars(Object.entries(d.charts.ordersByPlan||{}).map(([k,v])=>[k,v,v]))+'</div></div><div class="grid2">'+recentOrders(d.recentPurchases)+recentValidations(d.recentValidations)+'</div>';
    }
    function bars(items){ const max=Math.max(1,...items.map(x=>Number(x[2]||0))); return '<div class="bars">'+items.map(x=>'<div class="bar"><span>'+esc(x[0])+'</span><div class="bar-track"><div class="bar-fill" style="width:'+Math.max(4,Math.round((Number(x[2]||0)/max)*100))+'%"></div></div><strong>'+esc(x[1])+'</strong></div>').join('')+'</div>'; }
    function recentOrders(rows){ return '<div class="panel panel-pad"><h3>Recent purchases</h3>'+table(['Email','Plan','Amount','License'],rows.map(o=>'<tr><td>'+esc(maskEmail(o.customerEmail))+'</td><td>'+esc(o.plan)+'</td><td>'+money(o.amount,o.currency)+'</td><td><code>'+esc(maskCode(o.license?.licenseKey))+'</code></td></tr>'),'No purchases yet.')+'</div>'; }
    function recentValidations(rows){ return '<div class="panel panel-pad"><h3>Recent validations</h3>'+table(['License','Result','Reason','App'],rows.map(v=>'<tr><td><code>'+esc(maskCode(v.licenseKey))+'</code></td><td>'+pill(v.result)+'</td><td>'+esc(v.reason||'-')+'</td><td>'+esc(v.appVersion||'-')+'</td></tr>'),'No validation logs yet.')+'</div>'; }

    async function loadProducts(){ setLoading('products'); const d=await api('/admin/api/products'); $('products').innerHTML='<div class="panel panel-pad"><h3>Create product</h3><div class="grid3"><input id="prodName" placeholder="Product name"><input id="prodCategory" placeholder="Category"><input id="prodAmount" placeholder="Price cents EUR, e.g. 1499"></div><textarea id="prodDescription" placeholder="Description"></textarea><input id="prodImage" placeholder="Image URL"><div class="form-actions"><label class="check-row"><input type="checkbox" id="prodActive" checked> Active</label><button class="btn primary" onclick="createProduct()">Create Stripe product + price</button></div></div>'+table(['Product','Category','Active','Stripe Product','Prices','Purchases','Actions'],d.products.map(p=>'<tr><td><strong>'+esc(p.name)+'</strong><div class="muted">'+esc(short(p.description||'',80))+'</div></td><td>'+esc(p.category||'-')+'</td><td>'+pill(p.active?'active':'inactive')+'</td><td><code>'+esc(short(p.stripeProductId,22))+'</code></td><td>'+p.prices.map(pr=>money(pr.amount,pr.currency)+' '+(pr.active?'active':'old')).join('<br>')+'</td><td>'+esc(p.purchases?.length||0)+'</td><td class="actions"><input id="price_'+p.id+'" placeholder="New EUR cents"><button class="btn" onclick="changePrice(\\''+p.id+'\\')">New Price</button><button class="btn" onclick="toggleProduct(\\''+p.id+'\\','+(!p.active)+')">'+(p.active?'Disable':'Enable')+'</button></td></tr>'),'No products yet.'); }
    async function createProduct(){ await post('/admin/api/products',{name:prodName.value,category:prodCategory.value,description:prodDescription.value,image:prodImage.value,amount:prodAmount.value,active:prodActive.checked}); loadProducts(); }
    async function changePrice(id){ const input=document.getElementById('price_'+id); await post('/admin/api/products/'+id+'/price',{amount:input.value}); loadProducts(); }
    async function toggleProduct(id, active){ const row=(await api('/admin/api/products')).products.find(p=>p.id===id); await post('/admin/api/products/'+id,{name:row.name,description:row.description,category:row.category,image:row.image,active}); loadProducts(); }

    async function loadUsers(){ setLoading('users'); const d=await api('/admin/api/users'); $('users').innerHTML=table(['Email','Role','Stripe Customer','Created','Recent purchases'],d.users.map(u=>'<tr><td>'+esc(maskEmail(u.email))+'</td><td>'+esc(u.role)+'</td><td><code>'+esc(maskId(u.stripeCustomerId))+'</code></td><td>'+date(u.createdAt)+'</td><td>'+esc((u.purchases||[]).map(p=>p.product?.name||p.productId).join(', ')||'-')+'</td></tr>'),'No registered users yet.'); }

    async function loadPurchases(){ setLoading('purchases'); const d=await api('/admin/api/purchases'); $('purchases').innerHTML=table(['User','Product','Amount','Status','Stripe Session','Payment Intent','Created'],d.purchases.map(p=>'<tr><td>'+esc(maskEmail(p.user?.email||'-'))+'</td><td>'+esc(p.product?.name||p.productId)+'</td><td>'+money(p.amountTotal,p.currency)+'</td><td>'+pill(p.status)+'</td><td><code>'+esc(maskId(p.stripeCheckoutSessionId))+'</code></td><td><code>'+esc(maskId(p.stripePaymentIntentId))+'</code></td><td>'+date(p.createdAt)+'</td></tr>'),'No product purchases yet.'); }

    async function loadOrders(){ setLoading('orders'); $('orders').innerHTML=filters('orders') + '<div id="ordersTable"></div>'; await refreshOrdersTable(); }
    function filters(kind){ return '<div class="panel panel-pad"><div class="filters"><input id="'+kind+'Search" placeholder="Search email, license or Stripe ID"><select id="'+kind+'Plan"><option value="">All plans</option><option value="1day">Legacy Trial (history only)</option><option value="3days">3 Days Access</option><option value="monthly">Monthly Subscription</option><option value="lifetime">Lifetime</option><option value="2weeks">Legacy Product - 15 Days</option><option value="1month">Legacy Product - 1 Month</option><option value="3months">Legacy Product - 3 Months</option></select><select id="'+kind+'Status"><option value="">All statuses</option><option>active</option><option>inactive</option><option>banned</option><option>paid</option><option>unpaid</option></select><select id="'+kind+'Mode"><option value="">Any mode</option><option>live</option><option>test</option></select><button class="btn primary" onclick="refresh'+kind[0].toUpperCase()+kind.slice(1)+'Table()">Search</button></div></div>'; }
    async function refreshOrdersTable(){ const q=new URLSearchParams({search:ordersSearch.value,plan:ordersPlan.value,status:ordersStatus.value,mode:ordersMode.value}); const d=await api('/admin/api/orders?'+q); $('ordersTable').outerHTML='<div id="ordersTable">'+table(['Email','Plan','Amount','Mode','Status','Stripe Session','License','Actions'],d.orders.map(o=>'<tr><td>'+esc(maskEmail(o.customerEmail))+'</td><td>'+esc(o.plan)+'</td><td>'+money(o.amount,o.currency)+'</td><td>'+pill(o.mode)+'</td><td>'+esc(o.status)+'</td><td><code>'+esc(maskId(o.stripeSessionId))+'</code></td><td><code>'+esc(maskCode(o.license?.licenseKey))+'</code></td><td><button class="btn" onclick="detail(\\'/admin/api/orders/'+o.id+'\\',\\'Order\\')">View</button></td></tr>'),'No orders yet.')+'</div>'; }

    async function loadLicenses(){ setLoading('licenses'); $('licenses').innerHTML=filters('licenses') + '<div id="licensesTable"></div>'; await refreshLicensesTable(); }
    async function refreshLicensesTable(){ const q=new URLSearchParams({search:licensesSearch.value,plan:licensesPlan.value,status:licensesStatus.value}); const d=await api('/admin/api/licenses?'+q); $('licensesTable').outerHTML='<div id="licensesTable">'+table(['License','Source','User','Plan','Status','Time left','Expires','HWID','Counts','Payment','Actions'],d.licenses.map(l=>'<tr><td><code>'+esc(maskCode(l.licenseKey))+'</code></td><td>'+esc(l.source||'-')+'</td><td>'+esc(maskEmail(l.userEmail||l.customerEmail||'-'))+'<div class="muted">'+esc(l.robloxUsername||'no roblox')+'</div></td><td>'+esc(l.plan)+'</td><td>'+pill(l.status)+'<div class="muted">'+esc(l.hwidStatus||'Unbound')+'</div></td><td><strong class="'+(l.timeLeftState==='expired'?'danger-text':l.timeLeftState==='warning'?'warn-text':'')+'">'+esc(l.timeLeft||'-')+'</strong></td><td>'+esc(l.lifetime?'Lifetime':date(l.expiresAt))+'</td><td><code>'+esc(maskId(l.hwid||'unbound'))+'</code></td><td>V '+esc(l.validationCount||0)+' / D '+esc(l.downloadCount||0)+'</td><td><code>'+esc(maskId(l.paymentSessionId||l.stripeSessionId||'-'))+'</code></td><td class="actions"><span class="muted">Copy locked</span><button class="btn" onclick="detail(\\'/admin/api/licenses/'+l.id+'\\',\\'License\\')">View</button><button class="btn" onclick="post(\\'/admin/api/licenses/'+l.id+'/reset-hwid\\',{}).then(refreshLicensesTable)">Reset HWID</button><button class="btn good" onclick="post(\\'/admin/api/licenses/'+l.id+'/status\\',{status:\\'active\\'}).then(refreshLicensesTable)">Unban</button><button class="btn danger" onclick="post(\\'/admin/api/licenses/'+l.id+'/status\\',{status:\\'banned\\'}).then(refreshLicensesTable)">Ban</button></td></tr>'),'No licenses yet.')+'</div>'; }

    async function loadCustomers(){ setLoading('customers'); const d=await api('/admin/api/customers'); $('customers').innerHTML=table(['Email','Orders','Spent','First purchase','Last purchase','Notes','Actions'],d.customers.map(c=>'<tr><td>'+esc(maskEmail(c.email))+'</td><td>'+esc(c.totalOrders)+'</td><td>'+money(c.totalSpent)+'</td><td>'+date(c.firstPurchaseAt)+'</td><td>'+date(c.lastPurchaseAt)+'</td><td>'+esc(short(c.notes||'-',28))+'</td><td class="actions"><span class="muted">Reveal requires step-up</span></td></tr>'),'No customers yet.'); }
    async function sendCustomerReset(email){ if(!confirm('Send password reset email to '+email+'?')) return; const d=await post('/admin/api/customers/'+encodeURIComponent(email)+'/password-reset',{}); showModal('Password reset',d); }
    async function loadDownloads(){ setLoading('downloads'); const d=await api('/admin/api/downloads'); const c=d.current; window.latestManifestPreview=c.manifest||{}; $('downloads').innerHTML='<div class="grid3"><div class="card"><span>Source</span><strong>'+esc(c.source)+'</strong></div><div class="card"><span>Version</span><strong>'+esc(c.version||'Unknown')+'</strong></div><div class="card"><span>File</span><strong>'+esc(c.fileName||'Fallback')+'</strong></div></div><div class="panel panel-pad"><h3>Download URL</h3><code>'+esc(c.downloadUrl)+'</code><h3>Release notes</h3><p class="muted">'+esc(c.releaseNotes||'No release notes in manifest.')+'</p><button class="btn" onclick="showModal(\\'latest.json\\',window.latestManifestPreview)">View manifest JSON</button></div>'+table(['License','Result','Reason','Version','Created'],d.recent.map(r=>'<tr><td><code>'+esc(short(r.licenseKey,20))+'</code></td><td>'+pill(r.result)+'</td><td>'+esc(r.reason||'-')+'</td><td>'+esc(r.version||'-')+'</td><td>'+date(r.createdAt)+'</td></tr>'),'No download logs yet.'); }
    async function loadSettings(){ setLoading('settings'); const d=await api('/admin/api/settings'); const s=d.settings; $('settings').innerHTML='<div class="panel panel-pad"><div class="grid2"><label class="form-label">Discord invite URL<input id="setDiscord" value="'+esc(s.discordInviteUrl||'')+'"></label><label class="form-label">Support email<input id="setSupport" value="'+esc(s.supportEmail||'')+'"></label><label class="form-label">Brand name<input id="setBrand" value="'+esc(s.brandName||'')+'"></label><label class="form-label">Announcement<input id="setBanner" value="'+esc(s.announcementBannerText||'')+'"></label></div><div class="grid3"><label class="check-row"><input type="checkbox" id="setMaintenance" '+(s.maintenanceMode?'checked':'')+'> Maintenance mode</label><label class="check-row"><input type="checkbox" id="setBannerOn" '+(s.announcementBannerEnabled?'checked':'')+'> Banner enabled</label><label class="check-row"><input type="checkbox" id="setPricing" '+(s.pricingVisible?'checked':'')+'> Pricing visible</label><label class="check-row"><input type="checkbox" id="setCheckout" '+(s.checkoutEnabled?'checked':'')+'> Checkout enabled</label><label class="check-row"><input type="checkbox" id="setDownload" '+(s.downloadEnabled?'checked':'')+'> Download enabled</label></div><div class="form-actions"><button class="btn primary" onclick="saveSettings()">Save settings</button></div></div>'; }
    async function saveSettings(){ await post('/admin/api/settings',{discordInviteUrl:setDiscord.value,supportEmail:setSupport.value,brandName:setBrand.value,announcementBannerText:setBanner.value,maintenanceMode:setMaintenance.checked,announcementBannerEnabled:setBannerOn.checked,pricingVisible:setPricing.checked,checkoutEnabled:setCheckout.checked,downloadEnabled:setDownload.checked}); loadSettings(); }
    async function loadCoupons(){ setLoading('coupons'); const d=await api('/admin/api/coupons'); $('coupons').innerHTML='<div class="panel panel-pad"><h3>Create discount code</h3><div class="grid3"><input id="couponCode" placeholder="Code, e.g. FIMA10"><input id="couponPercent" placeholder="Percent off"><input id="couponAmount" placeholder="Amount off cents EUR"></div><div class="grid3"><input id="couponMax" placeholder="Max redemptions"><input id="couponExpiry" type="datetime-local"><input id="couponNotes" placeholder="Admin notes"></div><div class="form-actions"><label class="check-row"><input type="checkbox" id="couponActive" checked> Active</label><button class="btn primary" onclick="saveCoupon()">Create Stripe coupon + promo code</button></div></div>'+table(['Code','Stripe coupon','Stripe promo','Percent','Amount','Active','Expiry','Actions'],d.coupons.map(c=>'<tr><td>'+esc(c.code)+'</td><td><code>'+esc(short(c.stripeCouponId,20))+'</code></td><td><code>'+esc(short(c.stripePromotionCodeId,20))+'</code></td><td>'+esc(c.percentOff||'-')+'</td><td>'+esc(c.amountOff?money(c.amountOff,c.currency||'eur'):'-')+'</td><td>'+pill(c.active?'active':'inactive')+'</td><td>'+date(c.expiresAt)+'</td><td><button class="btn" onclick="couponStatus(\\''+c.id+'\\','+(!c.active)+')">'+(c.active?'Disable':'Enable')+'</button></td></tr>'),'No coupons yet.'); }
    async function saveCoupon(){ await post('/admin/api/coupons',{code:couponCode.value,percentOff:couponPercent.value,amountOff:couponAmount.value,maxRedemptions:couponMax.value,expiresAt:couponExpiry.value,active:couponActive.checked,notes:couponNotes.value}); loadCoupons(); }
    async function couponStatus(id, active){ await post('/admin/api/coupons/'+id+'/status',{active}); loadCoupons(); }
    let giftAdminPermissions=null; window.createdGiftCodeBuffer=[];
    async function getGiftAdminPermissions(){ if(giftAdminPermissions) return giftAdminPermissions; try{ const d=await api('/admin/api/gift-codes/permissions'); giftAdminPermissions=d.permissions||{}; } catch(e){ giftAdminPermissions={creationLocked:true,canCreateGiftCodes:false,canCreateDisposableTestCodes:false,canCreateLifetimeGifts:false,canBulkCreateGifts:false,canRevokeGiftCodes:false,maxBulkQuantity:1,maxUses:1}; } return giftAdminPermissions; }
    function giftPlanOptions(p){ return '<option value="3days">3 Days Access</option><option value="monthly">Monthly Subscription</option>'+(p.canCreateLifetimeGifts?'<option value="lifetime">Lifetime</option>':''); }
    function giftPermissionNotice(p){ const flags=p.requiredEnvFlags||{}; return '<div class="panel panel-pad"><h3>Gift code creation locked</h3><p class="muted">Creation, disposable test codes, lifetime gifts, bulk creation and revocation require explicit gift admin permissions. Normal users can only redeem gift codes or view their own purchased codes.</p><div class="grid3"><div class="card"><span>Create</span><strong>'+esc(p.canCreateGiftCodes?'enabled':'locked')+'</strong></div><div class="card"><span>Bulk</span><strong>'+esc(p.canBulkCreateGifts?'enabled':'locked')+'</strong></div><div class="card"><span>Lifetime</span><strong>'+esc(p.canCreateLifetimeGifts?'enabled':'locked')+'</strong></div></div><p class="muted">Required env flags: '+esc([flags.create,flags.disposableTest,flags.lifetime,flags.bulk,flags.revoke].filter(Boolean).join(', ')||'not configured')+'</p></div>'; }
    function renderCreatedGiftCodes(data){ const list=(data.giftCodes||(data.giftCode?[data.giftCode]:[])); const full=list.map(g=>g.code).filter(Boolean); window.createdGiftCodeBuffer=full; const masked=list.map(g=>'<li><code>'+esc(g.maskedCode||'masked')+'</code> '+esc(g.planLabel||g.plan||'')+'</li>').join(''); giftCreated.innerHTML='<strong>Created '+esc(list.length)+' gift code(s).</strong><p class="muted">Full code values are available only for this creation session. Lists and audit views stay masked.</p>'+(full.length?'<button class="btn good" id="copyCreatedGiftCodesOnce" onclick="copyCreatedGiftCodesOnce()">Copy full code(s) once</button>':'')+'<ul>'+masked+'</ul>'; }
    async function copyCreatedGiftCodesOnce(){ const text=(window.createdGiftCodeBuffer||[]).join('\\n'); if(!text) return; await navigator.clipboard?.writeText(text); window.createdGiftCodeBuffer=[]; const btn=$('copyCreatedGiftCodesOnce'); if(btn){ btn.disabled=true; btn.textContent='Copied once'; } }
    async function loadGiftCodes(){ setLoading('giftCodes'); const p=await getGiftAdminPermissions(); const createPanel=p.canCreateGiftCodes?'<div class="panel panel-pad"><h3>Create gift codes</h3><div class="grid3"><select id="giftPlan">'+giftPlanOptions(p)+'</select><input id="giftQuantity" type="number" min="1" max="'+esc(p.maxBulkQuantity||1)+'" value="1" placeholder="Quantity"><input id="giftMaxUses" type="number" min="1" max="'+esc(p.maxUses||1)+'" value="1" placeholder="Max uses"></div><div class="grid3"><input id="giftExpires" type="datetime-local"><input id="giftRecipientEmail" placeholder="Optional recipient email"><input id="giftRecipientUserId" placeholder="Optional recipient user id"></div><div class="grid3"><input id="giftNotes" placeholder="Admin note"><div class="muted">Gift creation is audited. Full codes are shown once after creation, then masked in lists.</div>'+(p.canCreateDisposableTestCodes?'<button class="btn good" onclick="createDisposableTestGiftCode()">Create Disposable Test Gift Code</button>':'<div class="muted">Disposable test code creation locked.</div>')+'</div><button class="btn primary" onclick="createGiftCodes()">Create gift code</button><div class="detail" id="giftCreated"></div></div>':giftPermissionNotice(p); $('giftCodes').innerHTML=createPanel+'<div class="panel panel-pad"><div class="filters"><input id="giftSearch" placeholder="Search masked code, plan or email"><select id="giftStatus"><option value="">All statuses</option><option>unused</option><option>active</option><option>redeemed</option><option>revoked</option></select><button class="btn primary" onclick="refreshGiftCodesTable()">Search</button></div></div><div id="giftCodesTable"></div>'; await refreshGiftCodesTable(); }
    async function createGiftCodes(){ const q=Number(giftQuantity.value||1); const plan=giftPlan.value; if(!confirm('You are about to create '+q+' gift code(s) for '+plan+'. Continue?')) return; const d=await post('/admin/api/gift-codes/create',{plan,quantity:q,maxUses:giftMaxUses.value,expiresAt:giftExpires.value,recipientEmail:giftRecipientEmail.value,recipientUserId:giftRecipientUserId.value,requiresDiscord:false,requiresRoblox:false,notes:giftNotes.value,confirmGiftCreation:true}); renderCreatedGiftCodes(d); await refreshGiftCodesTable(); }
    async function createDisposableTestGiftCode(){ if(!confirm('Create one short-expiring disposable test gift code?')) return; const d=await post('/admin/api/gift-codes/create-test',{plan:giftPlan.value,confirmGiftCreation:true}); renderCreatedGiftCodes(d); await refreshGiftCodesTable(); }
    async function refreshGiftCodesTable(){ const p=giftAdminPermissions||await getGiftAdminPermissions(); const q=new URLSearchParams({search:giftSearch.value,status:giftStatus.value}); const d=await api('/admin/api/gift-codes?'+q); giftAdminPermissions=d.permissions||p; $('giftCodesTable').outerHTML='<div id="giftCodesTable">'+table(['Code','Plan','Status','Uses','Requirements','Recipient','Redeemed by','Expires','Actions'],d.giftCodes.map(g=>'<tr><td><code>'+esc(g.maskedCode)+'</code></td><td>'+esc(g.planLabel||g.plan)+'</td><td>'+pill(g.status)+'</td><td>'+esc(g.usedCount)+' / '+esc(g.maxUses)+'</td><td>Discord '+esc(g.requiresDiscord?'required':'optional')+'<br>Roblox '+esc(g.requiresRoblox?'required':'optional')+'</td><td>'+esc(g.recipientEmail||'-')+'</td><td>'+esc((g.redemptions||[]).map(r=>r.email||r.user?.email||'-').join(', ')||'-')+'</td><td>'+date(g.expiresAt)+'</td><td class="actions"><button class="btn" onclick="detail(\\'/admin/api/gift-codes?search='+encodeURIComponent(g.maskedCode)+'\\',\\'Gift code\\')">View</button>'+(giftAdminPermissions.canRevokeGiftCodes?'<button class="btn danger" onclick="revokeGiftCode(\\''+g.id+'\\')">Revoke</button>':'<span class="muted">Revoke locked</span>')+'</td></tr>'),'No gift codes yet.')+'</div>'; }
    async function revokeGiftCode(id){ if(!confirm('Revoke this gift code?')) return; await post('/admin/api/gift-codes/'+id+'/revoke',{}); refreshGiftCodesTable(); }
    async function loadDirectGifts(){ setLoading('directGifts'); const p=await getGiftAdminPermissions(); const sendPanel=p.canCreateGiftCodes?'<div class="panel panel-pad"><h3>Send gift package</h3><div class="grid3"><input id="directEmail" placeholder="registered@email.com"><select id="directPlan"><option value="3days">3 Days Access</option><option value="7days">7 Days</option><option value="monthly">Monthly Subscription</option>'+(p.canCreateLifetimeGifts?'<option value="lifetime">Lifetime</option>':'')+'</select><input id="directExpires" type="datetime-local"></div><div class="grid3"><input id="directNotes" placeholder="Admin note"><div class="muted">Manual/direct gifts require explicit gift admin permissions and are audited.</div><div></div></div><textarea id="directMessage" placeholder="Message from Fieel"></textarea><button class="btn primary" onclick="sendDirectGift()">Send pending package</button><p class="muted" id="directResult"></p></div>':giftPermissionNotice(p); $('directGifts').innerHTML=sendPanel+'<div class="panel panel-pad"><div class="filters"><input id="directSearch" placeholder="Search email, plan, Discord or Roblox"><select id="directStatus"><option value="">All statuses</option><option>pending</option><option>claimed</option><option>expired</option><option>revoked</option></select><button class="btn primary" onclick="refreshDirectGiftsTable()">Search</button></div></div><div id="directGiftsTable"></div>'; await refreshDirectGiftsTable(); }
    async function sendDirectGift(){ if(!confirm('You are about to create a direct gift package for '+directPlan.value+'. Continue?')) return; const d=await post('/admin/api/direct-packages/send',{recipientEmail:directEmail.value,plan:directPlan.value,claimExpiresAt:directExpires.value,requiresDiscord:false,requiresRoblox:false,notes:directNotes.value,message:directMessage.value,confirmGiftCreation:true}); directResult.textContent='Pending package created for '+(d.package.recipientEmailFull||d.package.recipientEmail); await refreshDirectGiftsTable(); }
    async function refreshDirectGiftsTable(){ const p=giftAdminPermissions||await getGiftAdminPermissions(); const q=new URLSearchParams({search:directSearch.value,status:directStatus.value}); const d=await api('/admin/api/direct-packages?'+q); window.directGiftRows=d.packages||[]; $('directGiftsTable').outerHTML='<div id="directGiftsTable">'+table(['Recipient','Plan','Status','Requirements','Claim','License','Message','Actions'],window.directGiftRows.map((pck,i)=>'<tr><td>'+esc(pck.recipientEmail||'-')+'<div class="muted">'+esc(pck.recipientUser?.robloxUsername||pck.recipientUser?.discordUsername||'')+'</div></td><td>'+esc(pck.planLabel||pck.plan)+'</td><td>'+pill(pck.status)+'</td><td>Discord '+esc(pck.requiresDiscord?'required':'optional')+'<br>Roblox '+esc(pck.requiresRoblox?'required':'optional')+'</td><td>'+date(pck.claimedAt)+'<div class="muted">expires '+date(pck.claimExpiresAt)+'</div></td><td><code>'+esc(maskCode(pck.license?.licenseKey))+'</code></td><td>'+esc(short(pck.message||pck.notes||'-',60))+'</td><td class="actions"><button class="btn" onclick="showModal(\\'Direct gift\\',window.directGiftRows['+i+'])">View</button>'+(p.canRevokeGiftCodes?'<button class="btn danger" onclick="revokeDirectGift(\\''+pck.id+'\\')">Revoke</button>':'<span class="muted">Revoke locked</span>')+'</td></tr>'),'No direct gift packages yet.')+'</div>'; }
    async function revokeDirectGift(id){ if(!confirm('Revoke this pending/direct package?')) return; await post('/admin/api/direct-packages/'+id+'/revoke',{}); refreshDirectGiftsTable(); }
    async function loadReferrals(){ setLoading('referrals'); $('referrals').innerHTML='<div class="panel panel-pad"><div class="filters"><input id="referralsSearch" placeholder="Search code, email, Discord or Roblox"><select id="referralsStatus"><option value="">All statuses</option><option>pending</option><option>valid</option><option>rejected</option><option>flagged_for_review</option></select><button class="btn primary" onclick="refreshReferralsTable()">Search</button></div></div><div id="referralsTable"></div>'; await refreshReferralsTable(); }
    async function refreshReferralsTable(){ const q=new URLSearchParams({search:referralsSearch.value,status:referralsStatus.value}); const d=await api('/admin/api/referrals?'+q); $('referralsTable').outerHTML='<div id="referralsTable">'+table(['Code','Referrer','Referred user','Status','Checks','Reward','Created','Actions'],d.referrals.map(r=>'<tr><td><code>'+esc(r.code||'-')+'</code></td><td>'+esc(maskEmail(r.referrer?.email||'-'))+'<div class="muted">'+esc(r.referrer?.robloxUsername||r.referrer?.discordUsername||'')+'</div></td><td>'+esc(maskEmail(r.referred?.email||'-'))+'<div class="muted">'+esc(r.referred?.robloxUsername||r.referred?.discordUsername||'')+'</div></td><td>'+pill(r.status)+'<div class="muted">'+esc(r.statusReason||'-')+'</div></td><td>Discord '+esc(r.verification?.discordConnected?'OK':'-')+'<br>Roblox '+esc(r.verification?.robloxConnected?'OK':'-')+'<br>Flags '+esc((r.flags||[]).length)+'</td><td>'+esc(r.rewardGranted?'Granted':'Not yet')+'</td><td>'+date(r.createdAt)+'</td><td class="actions"><button class="btn good" onclick="referralStatus(\\''+r.id+'\\',\\'valid\\')">Approve</button><button class="btn danger" onclick="referralStatus(\\''+r.id+'\\',\\'rejected\\')">Reject</button><button class="btn" onclick="referralStatus(\\''+r.id+'\\',\\'flagged_for_review\\')">Flag</button><button class="btn" onclick="detail(\\'/admin/api/referrals?search='+encodeURIComponent(r.code||r.id)+'\\',\\'Referral\\')">View</button></td></tr>'),'No referrals yet.')+'</div>'; }
    async function referralStatus(id,status){ const reason=prompt('Reason / note for '+status, 'manual_'+status) || 'manual_'+status; await post('/admin/api/referrals/'+id+'/status',{status,reason}); refreshReferralsTable(); }
    async function loadAnalytics(){ setLoading('analytics'); const d=await api('/admin/api/analytics'); $('analytics').innerHTML='<div class="grid2"><div class="panel panel-pad"><h3>Events by type</h3>'+bars(Object.entries(d.byType||{}).map(([k,v])=>[k,v,v]))+'</div><div class="panel panel-pad"><h3>Events by plan</h3>'+bars(Object.entries(d.byPlan||{}).map(([k,v])=>[k,v,v]))+'</div></div>'+table(['Type','Plan','Amount','Mode','Created'],d.events.slice(0,100).map(e=>'<tr><td>'+esc(e.type)+'</td><td>'+esc(e.plan||'-')+'</td><td>'+esc(e.amount?money(e.amount,e.currency):'-')+'</td><td>'+esc(e.mode||'-')+'</td><td>'+date(e.createdAt)+'</td></tr>'),'No analytics events yet.'); }
    async function loadWebhooks(){ setLoading('webhooks'); const d=await api('/admin/api/webhooks'); $('webhooks').innerHTML=table(['Event','Type','Processed','Error','Order','License','Created'],d.events.map(e=>'<tr><td><code>'+esc(short(e.stripeEventId,24))+'</code></td><td>'+esc(e.type)+'</td><td>'+pill(e.processed?'success':'failed')+'</td><td>'+esc(e.errorMessage||'-')+'</td><td>'+esc(short(e.relatedOrderId,12))+'</td><td>'+esc(short(e.relatedLicenseId,12))+'</td><td>'+date(e.createdAt)+'</td></tr>'),'No webhook events yet.'); }
    async function loadAudit(){ setLoading('audit'); const d=await api('/admin/api/audit'); $('audit').innerHTML=table(['Action','Target','Metadata','Created'],d.logs.map(l=>'<tr><td>'+esc(l.action)+'</td><td>'+esc((l.targetType||'-')+' '+(l.targetId||''))+'</td><td><code>'+esc(short(JSON.stringify(l.metadata||{}),80))+'</code></td><td>'+date(l.createdAt)+'</td></tr>'),'No audit logs yet.'); }
    async function loadPermissions(){ setLoading('permissions'); const d=await api('/admin/api/rbac/permissions'); const dangerous=new Set((d.permissions||[]).filter(p=>p.dangerous).map(p=>p.id)); const grouped=Object.entries(d.groups||{}).map(([group,permissions])=>'<div class="card"><span>'+esc(group)+'</span><strong>'+esc(permissions.length)+' permissions</strong><p class="muted">'+esc(permissions.join(', '))+'</p></div>').join(''); const roleCards=(d.roles||[]).map(role=>'<div class="panel panel-pad"><h3>'+esc(role.label)+' '+(role.locked?pill('locked'):'')+'</h3><p class="muted">'+esc(role.description||'')+'</p><div class="grid3">'+(role.permissions||[]).map(permission=>'<div class="card"><span>'+esc(permission.split('.')[0])+'</span><strong class="'+(dangerous.has(permission)?'warn-text':'')+'">'+esc(permission)+'</strong></div>').join('')+'</div>'+(role.deniedByDefault?.length?'<p class="muted"><strong>Denied by default:</strong> '+esc(role.deniedByDefault.join(', '))+'</p>':'')+'</div>').join(''); $('permissions').innerHTML='<div class="panel panel-pad"><h3>RBAC status</h3><p class="muted">Role presets are defined here. Next backend step is persistent per-user overrides and requirePermission(permission) enforcement on mutating routes. Owner lockout and secret masking stay required.</p><div class="grid3">'+grouped+'</div></div>'+roleCards; }
    function loadTools(){ $('tools').innerHTML='<div class="panel panel-pad"><h3>Manual license</h3><div class="grid3"><input id="manualEmail" placeholder="customer@example.com"><select id="manualPlan"><option value="3days">3 Days Access</option><option value="monthly" selected>Monthly Subscription</option><option value="lifetime">Lifetime</option><option value="2weeks">Legacy Product - 15 Days</option><option value="1month">Legacy Product - 1 Month</option><option value="3months">Legacy Product - 3 Months</option></select><button class="btn primary" onclick="manualLicense()">Create license</button></div><p class="muted" id="manualResult"></p></div><div class="panel panel-pad"><h3>License debug</h3><p class="muted">Dry-run validation does not bind HWID. Use this when a website, gift or manual key does not open the app.</p><div class="grid3"><input id="toolLicense" placeholder="FIMA-XXXX-XXXX-XXXX-XXXX"><input id="toolHwid" placeholder="Optional HWID"><button class="btn primary" onclick="testLicense()">Test license</button></div><div class="grid2" style="margin-top:10px"><button class="btn" onclick="testDownload()">Check download</button><button class="btn" onclick="copyDebugResult()">Copy debug result</button></div><div id="toolDebugSummary"></div><pre class="detail" id="toolResult"></pre></div>'; }
    async function manualLicense(){ const d=await post('/admin/api/licenses/manual',{customerEmail:manualEmail.value,plan:manualPlan.value}); manualResult.textContent='Created: '+maskCode(d.license.licenseKey); }
    let lastLicenseDebug=null;
    async function testLicense(){ const d=await post('/admin/api/licenses/validate',{licenseKey:toolLicense.value,hwid:toolHwid.value}); lastLicenseDebug=d; renderLicenseDebug(d); toolResult.textContent=JSON.stringify(d,null,2); }
    async function testDownload(){ const d=await api('/api/download?licenseKey='+encodeURIComponent(toolLicense.value)); toolResult.textContent=JSON.stringify(d,null,2); }
    function renderLicenseDebug(d){
      const found=Boolean(d.licenseId);
      const stateClass=d.valid?'good':'danger';
      const rows=[
        ['License found',found?'yes':'no'],['Source',d.source||'-'],['Status',d.status||'-'],['Plan',d.planName||d.plan||'-'],
        ['Expiry',d.lifetime?'Lifetime':date(d.expiresAt)],['Time left',d.timeLeft||'-'],['Bound HWID',d.boundHwid||'Unbound'],
        ['Given HWID matches',String(Boolean(d.hwidMatches))],['Account connected',String(Boolean(d.accountConnected))],
        ['Discord linked',String(Boolean(d.discordLinked))],['Roblox linked',String(Boolean(d.robloxLinked))],
        ['Can use app',String(Boolean(d.canUseApp))],['Backend reason',d.reason||'-'],['App message preview',d.appMessagePreview||d.message||'-'],
        ['Last validation',date(d.lastValidatedAt)],['Buyer email',d.buyerEmail||d.customerEmail||'-'],
        ['Buyer Discord',d.buyerDiscord?.username||d.discordUsername||'-'],['Buyer Roblox',d.buyerRoblox?.username||d.robloxUsername||'-']
      ];
      const actions=found?'<div class="actions" style="margin-top:12px"><button class="btn" onclick="detail(\\'/admin/api/licenses/'+d.licenseId+'\\',\\'License record\\')">Open license record</button><button class="btn" onclick="openBuyerFromDebug()">Open buyer</button><button class="btn" onclick="post(\\'/admin/api/licenses/'+d.licenseId+'/reset-hwid\\',{}).then(testLicense)">Reset HWID</button><button class="btn good" onclick="post(\\'/admin/api/licenses/'+d.licenseId+'/status\\',{status:\\'active\\'}).then(testLicense)">Re-enable license</button><button class="btn" onclick="addLicenseDebugNote()">Add admin note</button></div>':'';
      $('toolDebugSummary').innerHTML='<div class="panel panel-pad" style="margin-top:14px"><h3>Debug result '+pill(d.valid?'valid':'blocked')+'</h3><div class="grid3">'+rows.map(([k,v])=>'<div class="card"><span>'+esc(k)+'</span><strong class="'+stateClass+'-text">'+esc(v)+'</strong></div>').join('')+'</div>'+actions+'</div>';
    }
    function copyDebugResult(){ copyText(toolResult.textContent||JSON.stringify(lastLicenseDebug||{},null,2)); }
    async function openBuyerFromDebug(){ if(!lastLicenseDebug) return; if(lastLicenseDebug.buyerEmail||lastLicenseDebug.customerEmail) return detail('/admin/api/customers/'+encodeURIComponent(lastLicenseDebug.buyerEmail||lastLicenseDebug.customerEmail),'Buyer'); alert('No buyer email on this license.'); }
    async function addLicenseDebugNote(){ if(!lastLicenseDebug?.licenseId) return; const notes=prompt('Admin note for this license'); if(!notes) return; await post('/admin/api/licenses/'+lastLicenseDebug.licenseId+'/notes',{notes}); await testLicense(); }
    async function detail(path,title){ showModal(title, await api(path)); }
    async function post(path, body){ return api(path,{method:'POST',body:JSON.stringify(body||{})}); }
    function copyText(text){ navigator.clipboard?.writeText(text); }
    refreshCurrent();
  </script>
</body>
</html>`;
}

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (char) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;"
  })[char]);
}
